basePath: /api/v1
definitions:
  domain.Post:
    properties:
      author_id:
        type: string
      content:
        type: string
      create_at:
        type: string
      post_id:
        type: string
      tag_id:
        type: string
      title:
        type: string
      update_at:
        type: string
    type: object
  models.PostCreate:
    properties:
      author_id:
        type: string
      content:
        type: string
      tag_id:
        type: string
      title:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API tài liệu cho Social app
  title: Social API
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Trả về danh sách bài viết
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Post'
      summary: Lấy danh sách posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Trả về post created
      parameters:
      - description: Dữ liệu bài viết
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.PostCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Post'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Tạo mới post
      tags:
      - posts
swagger: "2.0"
