# Step 1: Modules caching
FROM golang:1.24.1-alpine3.20 as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.24.1-alpine3.20 as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
RUN go build -tags migrate -o /bin/app ./cmd/user

# Step 3: Final
FROM scratch

EXPOSE 5001

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/user/config.yml /
COPY --from=builder /bin/app /app
CMD ["/app"]