app:
  name: 'product-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 8081

postgres:
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'admin'
  database: 'postgres'

redis:
  host: 'localhost'
  port: 6379
